Repository SUIN404/Sass-workshop, pull requests merged in 2020-02, with the labels that each got.

#2 ajout footer
  css/style.css
  index.html
  sass/style.scss
Labels: enhancement

#3 Dev sara
  css/style.css
  index.html
  sass/style.scss
Labels: bug

#4 Add Imane files
  css/style.css
  index.html
  sass/style.scss
Labels: documentation
